    #   - name: Login to Azure
    #     uses: azure/login@v2
    #     with:
    #       client-id: ${{ secrets.__clientidsecretname__ }}
    #       tenant-id: ${{ secrets.__tenantidsecretname__ }}
    #       subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

    #   - name: 'Deploy to Azure Functions'
    #     uses: Azure/functions-action@v1
    #     id: deploy-to-function
    #     with:
    #       app-name: 'urlMaker'
    #       slot-name: 'Production'
    #       package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}